### ISSUE TITLE
On Centos 7 the version of docker-composed used is too old for Harbor

### ISSUE THREAD

**Issue by simonccc** [walkamongus/puppet-harbor#15]
On Centos7 using `mod 'puppetlabs-docker', '3.9.0'` version 1.9.0 of docker-compose is installed. This is too old eg

`ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/`

**Comment by walkamongus** [comment]
@simonccc This module pulls in `docker` and `docker::compose` with simple `include` statements, which means by default you get the version set as the default in those modules here: https://github.com/puppetlabs/puppetlabs-docker/blob/v3.9.0/manifests/params.pp#L38

You should be able to override this version by simply setting `docker::compose::version` wherever you set module data (most commonly in hiera)

**Comment by simonccc** [comment]
Thanks
