### ISSUE TITLE
Allow configuration of harbor-swagger-client with certificate bundle

### ISSUE THREAD

**Issue by entasisj** [walkamongus/puppet-harbor#21]
In order to have SSL connection (verify_ssl: true) to the harbor API working well if a self-signed cerificate is involved it is required to configure the harbor-swagger-client with "ssl_ca_cert" pointing to a certificate bundle (containing the self-signed certificate).

**Comment by entasisj** [comment]
I created pull request to address the issue: https://github.com/walkamongus/puppet-harbor/pull/23

**Comment by walkamongus** [comment]
fixed by #23  -- thanks @entasisj
