### ISSUE TITLE
Allow configuration of harbor-swagger-client with host

### ISSUE THREAD

**Issue by entasisj** [walkamongus/puppet-harbor#22]
In order to have SSL verification (verify_ssl_host: true) to the host running the harbor API it is required to configure the harbor-swagger-client with "host". The problem here is that the default value is 'localhost' which fails the verification.

**Comment by entasisj** [comment]
I created a pull request to address the issue: https://github.com/walkamongus/puppet-harbor/pull/23

**Comment by walkamongus** [comment]
fixed by #23 -- thanks @entasisj !
